//This file was generated by `npm run generate:types`

export type DiceRollDemoSimOptions = {
	/** The maximum number on the die face */
	die?: number;
	/** The score we try to hit to win */
	targetScore?: number;
	/** The die number that, if it comes up, will bust */
	bust?: number;
};