//This file was generated by `npm run generate:types`

import {
	DistributionOptions
} from '../../types.js';

export type FreeMovingAgentsSimOptions = {
	/** Optional display properties */
	display?: {
		/** Render debug bounds for coordinates map */
		bounds?: boolean;
	};
	/** Information on agents */
	agents?: {
		/** The number of starter agents */
		count?: number;
		/** The starter strength of agents that start at the beginning */
		speed?: DistributionOptions;
		/** What emoji to use for the agents */
		emoji?: '🐞' | '🕷️' | '🦋' | '🪲' | '🪳' | '🪰' | '🪱' | '🐜' | '🐛' | '🐝' | '🦗' | '🦟' | '🐌' | '🦂';
	};
	/** The number of rounds */
	rounds?: number;
};