//This file was generated by `npm run generate:types`

export type WildflowerMeadowSimOptions = {
	/** Number of rows in the meadow */
	rows: number;
	/** Number of columns in the meadow */
	cols: number;
	/** Probability per frame for edge bare/fertile cells to spawn a weed */
	weedSpawnRate: number;
	/** Probability per adjacent weed neighbor to convert bare/fertile/wilting cells */
	weedSpreadRate: number;
	/** Probability per adjacent blooming neighbor to seed bare/fertile cells */
	basePollination: number;
	/** Frames a flower stays blooming */
	bloomDuration: number;
	/** Frames as seed before growing */
	seedGrowthTime: number;
	/** Frames as growing before blooming */
	growGrowthTime: number;
	/** Frames wilting before becoming fertile soil */
	wiltDuration: number;
};