//This file was generated by 'npm run generate:config'

export const KNOWN_DATA_FILES = [
	'default',
	'schelling-org'
];

export type SimulatorType = '' | 'dice-roll-demo' | 'luck-surface-area' | 'pasture-demo' | 'schelling-org' | 'standing-ovation';

export const KNOWN_SIMULATOR_TYPES : SimulatorType[] = [
	'dice-roll-demo',
	'luck-surface-area',
	'pasture-demo',
	'schelling-org',
	'standing-ovation'
];