//This file was generated by 'npm run generate:config'

//All of these exports are also re-exported from src/types.ts, so you should import them from there.

export const KNOWN_DATA_FILES = [
	'default',
	'schelling-org'
];

export type SimulatorType = '' | 'dice-roll-demo' | 'luck-surface-area' | 'pasture-demo' | 'schelling-org' | 'standing-ovation' | 'stub';

export const KNOWN_SIMULATOR_TYPES : SimulatorType[] = [
	'dice-roll-demo',
	'luck-surface-area',
	'pasture-demo',
	'schelling-org',
	'standing-ovation',
	'stub'
];